Repository Webler-Group/webler-codes, pull requests merged in 2024-07, with the labels that each got.

#1 first commit in paul's branch
  .gitignore
  README.md
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/footer.tsx
  frontend/src/components/metas.tsx
  frontend/src/components/nav.tsx
  frontend/src/pages/about.tsx
  frontend/src/pages/home.tsx
  frontend/src/pages/login.tsx
Labels: enhancement

#3 my commit
  backend/README.md
Labels: documentation

#2 Update readme DAVID
  README.md
Labels: enhancement

#5 removed usless edits
  README.md
  backend/README.md
Labels: bug

#8 added sass setup
  frontend/package-lock.json
  frontend/package.json
  frontend/src/index.scss
Labels: enhancement
